export App from './App/App';
export AppBar from './AppBar/AppBar';
export AuthorizedArea from './AuthorizedArea/AuthorizedArea';
export Settings from './Settings/Settings';
export Home from './Home/Home';
export Login from './Login/Login';
export Main from './Main/Main';
export Result from './Result/Result';
export Survey from './Survey/Survey';
